# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform jointGHS with ECM
#' 
#' This function performs expectation-conditional-maximation or iterated conditional mode estimation for the joint graphical horseshoe
#' 
#' @param S cube of the \eqn{p} by \eqn{p} scatter matrices of the \eqn{K} data sets
#' @param theta cube of the \eqn{K} initial \eqn{p} by \eqn{p} precision matrices
#' @param sigma cube of the \eqn{K} initial \eqn{p} by \eqn{p} covariance matrices
#' @param Lambda_sq cube of the \eqn{K} initial \eqn{p} by \eqn{p} matrices of squared local shrinkage parameters
#' @param N vector of length \eqn{K} of the number of obervations in each data set. 
#' @param M the number of variables/nodes. Integer
#' @param K the number of networks. Integer
#' @param epsilon tolerance for the convergence assessment
#' @param verbose logical indicator of printing information at each iteration
#' @param maxitr maximum number of iterations
#' @param savepath logical indicator of saving the estimator at each iteration in the ECM algorithm. Only available for p<200
#' @param save_Q should the value of the objective function at each step be saved?
#' @param tau_sq vector of initial values of the \eqn{K} squared global shrinkage parameters
#' @param use_ICM logical. Should ICM be used instead of ECM? Default value is false
#' @param fix_tau logical. Should tau be fixed?
#' 
#' @return A List with resulting ECM estimates, and saved path and objective function convergence information if requested
#' 
#' @export
#'
ECM_GHS <- function(S, theta, sigma, Lambda_sq, N, M, K, epsilon, verbose, maxitr, savepath, save_Q, tau_sq, use_ICM = FALSE, fix_tau = TRUE) {
    .Call(`_jointGHS_ECM_GHS`, S, theta, sigma, Lambda_sq, N, M, K, epsilon, verbose, maxitr, savepath, save_Q, tau_sq, use_ICM, fix_tau)
}

