# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform GHS with ECM
#' 
#' This function performs expectation-conditional-maximation or iterated conditional mode estimation for the graphical horseshoe
#' 
#' @param X \eqn{n} by \eqn{p} matrix of data
#' @param S \eqn{p} by \eqn{p} scatter matrix of the data
#' @param theta initial value of the \eqn{p} by \eqn{p} precision matrix
#' @param sigma initial value of the \eqn{p} by \eqn{p} covariance matrix
#' @param Lambda_sq initial value of matrix of squared local shrinkage parameters
#' @param epsilon tolerance for the convergence assessment
#' @param verbose logical indicator of printing information at each iteration
#' @param maxitr maximum number of iterations
#' @param savepath logical indicator of saving the estimator at each iteration in the ECM algorithm. Only available for p<200
#' @param exist_group logical. Are the variables grouped?
#' @param group grouping information.
#' @param N_groups If exist_group==T, the number of groups
#' @param save_Q should the value of the objective function at each step be saved?
#' @param tau_sq initial value of squared global shrinkage parameter. If exist_group==T, a dummy value should be provided
#' @param Tau_sq if exist_group==T, an \eqn{ngroup} by \eqn{ngroup} matrix of initial values of the squared global shrinkage parameters within and between groups. If exist_group==F, a dummy value should be provided
#' @param machine_eps numerical. The machine precision
#' @param use_ICM logical. Should ICM be used instead of ECM? Default value is false
#' 
#' @return A List with resulting ECM estimates, and saved path and objective function convergence information if requested
#' 
#' @export
ECM_GHS <- function(S, theta, sigma, Lambda_sq, N, M, K, epsilon, verbose, maxitr, savepath, save_Q, tau_sq, use_ICM = FALSE, fix_tau = FALSE) {
    .Call(`_jointGHS_ECM_GHS`, S, theta, sigma, Lambda_sq, N, M, K, epsilon, verbose, maxitr, savepath, save_Q, tau_sq, use_ICM, fix_tau)
}

